### ISSUE TITLE
Not packages published

### ISSUE THREAD

**Issue by Suavesito-Olimpiada** [skynetcap/solanaj#1]
I'm trying to use this library for experimenting, but I cannot get it to work with maven given that there are not packages published. :sweat_smile: 

Is there a plan to publish the builds? :thinking:

**Comment by skynetcap** [comment]
They are published now as 

```
<dependency>
      <groupId>com.mmorrell</groupId>
      <artifactId>solanaj</artifactId>
      <version>1.10</version>
</dependency>
```
Thanks
