### ISSUE TITLE
RewardType.Class Json exception

### ISSUE THREAD

**Issue by IsaGULER** [skynetcap/solanaj#15]
I am trying on Solana Testnet, and when I use getBlock() method I got Json parsing exception.
```
public enum RewardType {
    /*FEE, RENT, VOTING, STAKING*/
    Fee, Rent, Voting, Staking
}
```
exception occurs because of upper case and when I change like this it works.

Thanks in advance.

**Comment by skynetcap** [comment]
Fixed in SolanaJ 1.12, and released.
