### ISSUE TITLE
Version 2.0 Discussion

### ISSUE THREAD

**Issue by skynetcap** [skynetcap/solanaj#23]
Requirements:

Architecture:
- Replace Exception-based code with Optionals, remove try-catch from normal code flow.
- Evaluate different Websocket libraries
- Support for importing/signing/sending raw transactions (Base64/bytes)
- Support for durable nonces
- Mechanism for auto-reconnect on Websockets + re-subscribe to dropped subscriptions
- SOCKS proxy support

APIs:
- Coverage of the newer APIs
- Support ALTs (Address Lookup Tables)

GetProgramAccounts:
- Support pagination using `dataSize = 0`

**Comment by skynetcap** [comment]
- Support for importing/signing/sending raw transactions (Base64/bytes)

**Comment by skynetcap** [comment]
- Support for durable nonces

**Comment by skynetcap** [comment]
- Mechanism for auto-reconnect on Websockets + re-subscribe to dropped subscriptions

**Comment by skynetcap** [comment]
- Websocket automatic reconnect on close
- SOCKS proxy support

**Comment by itsmelodewyk** [comment]
Support for [VersionedTransactions](https://solana.com/docs/core/transactions/versions) - attempting to modify existing code as we speak. Hopefully a PR isn't too far down the road.

**Comment by skynetcap** [comment]
In 1.18.0-staging branch, I've implemented:

- SOCKS proxy support
- WebSocket auto-reconnect and auto-resubscribe.
- WebSocket unsubscribe APIs

**Comment by skynetcap** [comment]
Closing this issue in favor of separate issues/tickets for each feature.

Remaining work to be spun out:

GetProgramAccounts:
- Support pagination using `dataSize = 0`

APIs:
- Support ALTs (Address Lookup Tables)
- Replace Exception-based code with Optionals, remove try-catch from normal code flow. (This will be V2/major version upgrade.)
- Support for importing/signing/sending raw transactions (Base64/bytes)
