### ISSUE TITLE
How to parse serialized data?

### ISSUE THREAD

**Issue by ovicloud** [skynetcap/solanaj#27]
var transaction = VersionedTransaction.deserialize(swapTransactionBuf);
How to implement it in Java?

**Comment by skynetcap** [comment]
I don't think there's a native deserialize yet (feel free to add), but you can send it to `simulateTransaction` and get info from that.

**Comment by Mykke24** [comment]
[https://github.com/itsmelodewyk/java-jup-ag/blob/f0ee3d1bd95a3b0fa18e42ea18d94c96bab814c9/src/main/java/utils/VersionedTransaction.java#L42](url)


this might help you

**Comment by jekka001** [comment]
Why can't I see anything on the link above?
Where is VersionedTransaction for java ? :(

**Comment by bestRunner** [comment]
> 为什么我在上面链接上看不到任何内容？ Java 的 VersionedTransaction 在哪里？:(

Have you found a solution yet @jekka001

**Comment by jekka001** [comment]
> > 为什么我在上面链接上看不到任何内容？ Java 的 VersionedTransaction 在哪里？:(
> 
> Have you found a solution yet @jekka001

No, this solution is not exist.

Now, I'm writing my own solution and I think It will be work

**Comment by chintanpatel2634** [comment]
Any updates on this issue if anyone has found a solution? I am trying to deserialize Jupiter's swap API response.

**Comment by jekka001** [comment]
> Any updates on this issue if anyone has found a solution? I am trying to deserialize Jupiter's swap API response.

Yes I found solution, but I'm not ready to share it

**Comment by chintanpatel2634** [comment]
Cool. I am also working on my solution and will share it here once I get it.

**Comment by chintanpatel2634** [comment]
I have a solution here that deserializes the transaction. I also added the Jupiter program to swap tokens that use the deserializer. Feel free to give any feedback. 
https://github.com/chintanpatel2634/solanaj/pull/1/files
