### ISSUE TITLE
how do use proxy

### ISSUE THREAD

**Issue by printhellow** [skynetcap/solanaj#31]
how do use proxy in RpcClient？

**Comment by liuruibin1** [comment]
Override RpcClient
Call like this： RpcClientProxy client = new RpcClientProxy(true, Cluster.MAINNET);

**Comment by liuruibin1** [comment]
refer to：https://github.com/liuruibin1/solanaj/blob/main/src/main/java/org/p2p/solanaj/rpc/RpcClientProxy.java

**Comment by skynetcap** [comment]
SOCKS proxy support added in `1.18-staging`
