### ISSUE TITLE
 When using version 1.14, an error occurs when calling the getBlock method

### ISSUE THREAD

**Issue by wangdachui444777** [skynetcap/solanaj#32]
org.p2p.solanaj.rpc.RpcException: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0
	at org.p2p.solanaj.rpc.RpcClient.call(RpcClient.java:88)
	at org.p2p.solanaj.rpc.RpcApi.getBlock(RpcApi.java:522)

**Comment by skynetcap** [comment]
Fixed here: https://github.com/skynetcap/solanaj/commit/d97fe203e564026d9ddae42a9c209dc9e35a4d74

Will be built into a release shortly.

**Comment by roway168** [comment]
#34
