### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roway168** [skynetcap/solanaj#34]
[org.p2p.solanaj.programs.AssociatedTokenProgram](https://github.com/skynetcap/solanaj/blob/a7660140cad2efb400dc4f00e3881923bb3ba3ac/src/main/java/org/p2p/solanaj/programs/AssociatedTokenProgram.java#L43)

keys.add(new AccountMeta(walletAddress, false, false));

**Comment by skynetcap** [comment]
Fixed

**Comment by roway168** [comment]
perfect !
﻿
