### ISSUE TITLE
createAssociatedTokenAccountInstruction

### ISSUE THREAD

**Issue by ImL1s** [skynetcap/solanaj#36]
Is there any implementation of the createAssociatedTokenAccountInstruction method? I can’t seem to find it under TokenProgram

**Comment by Mykke24** [comment]
here you go

`	private TransactionInstruction createAssociatedTokenAccountIdempotentInstruction(PublicKey payer, PublicKey associatedToken, PublicKey owner, PublicKey mint, PublicKey programId, PublicKey associatedTokenProgramId) {
		byte[] buffer = { 1 };
		return build_AssociatedTokenAccountInstruction( //
				payer, //
				associatedToken, //
				owner, //
				mint, //
				buffer, //
				programId, //
				associatedTokenProgramId//
		);
	}`

`private TransactionInstruction build_AssociatedTokenAccountInstruction( //
			PublicKey payer, //
			PublicKey associatedToken, //
			PublicKey owner, //
			PublicKey mint, //
			byte[] buffer, //
			PublicKey programId, //
			PublicKey associatedTokenProgramId//
	) {
		ArrayList<TS_AccountMeta> accountMetaKeys = new ArrayList<TS_AccountMeta>();
		accountMetaKeys.add(new TS_AccountMeta(payer.toBase58(), true, true));
		accountMetaKeys.add(new TS_AccountMeta(associatedToken.toBase58(), false, true));
		accountMetaKeys.add(new TS_AccountMeta(owner.toBase58(), false, false));
		accountMetaKeys.add(new TS_AccountMeta(mint.toBase58(), false, false));
		accountMetaKeys.add(new TS_AccountMeta(SystemProgram.PROGRAM_ID.toBase58(), false, false));
		accountMetaKeys.add(new TS_AccountMeta(programId.toBase58(), false, false));

		TransactionInstruction ti = new TransactionInstruction(associatedTokenProgramId.toBase58(), accountMetaKeys, buffer);
		return ti;
	}`

**Comment by LogicPush** [comment]
Hello! have you found a way please?
