### ISSUE TITLE
getTransaction error

### ISSUE THREAD

**Issue by bliplink** [skynetcap/solanaj#38]
public ConfirmedTransaction getTransaction(String signature, Commitment commitment) throws RpcException {
        List<Object> params = new ArrayList<>();
        params.add(signature);
        Map<String, Object> parameterMap = new HashMap<>();

        if (commitment != null) {
            parameterMap.put("commitment", commitment); //update  parameterMap.put("commitment", commitment.getValue());
        }

        parameterMap.put("maxSupportedTransactionVersion", 0);
        params.add(parameterMap);
        return client.call("getTransaction", params, ConfirmedTransaction.class);
    }

**Comment by skynetcap** [comment]
Can you provide the full error and an example test case (example TX)? I can't reproduce this.
