### ISSUE TITLE
Want

### ISSUE THREAD

**Issue by blate666** [skynetcap/solanaj#44]
I think your project is very good. It would be great if you could have more examples of splTopken transfers.

**Comment by skynetcap** [comment]
Thanks. I'm currently accelerating/rebooting development on this project after having took some time off.

**Comment by skynetcap** [comment]
Added some example usage here: https://github.com/skynetcap/solanaj/blob/1.18.0-staging/src/test/java/org/p2p/solanaj/manager/TokenManagerTest.java

Feel free to open a new issue as needed.
