### ISSUE TITLE
Java 17 Oracle Subscription

### ISSUE THREAD

**Issue by ExOCeo** [skynetcap/solanaj#45]
If the client will need modern Java 17 security patches or features in the future and I am running a client, do I need to pay the subscription fee for that?  Just wondering how to make the judgment that a blockchain network client run by a community member is considered for personal use or commercial purposes.

**Comment by skynetcap** [comment]
IIRC OpenJDK provides free implementations of the JVM and has no subscription fee. OpenJDK is also used at big companies. Oracle licensing/support is not required. 

More info: https://openjdk.org/
