### ISSUE TITLE
How to get account from, account to and transaction amout from ConfirmedTransaction

### ISSUE THREAD

**Issue by b3lowster** [skynetcap/solanaj#46]
I have a usdt transfer transaction and It's not clear how to get account from (account to) and amount of transaction,

I can assume that the first accountKey from accountKeys from a message is an account from, Am I right?
Might be I can calculate transaction amount base on token balances from meta information?

Thanks a lot

**Comment by skynetcap** [comment]
To get a `from` and `to` for a token transfers TX, you need to get the TX, go through each instruction <> compare if it is the Token Program `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`, then deserialize token amount, and get public keys at fixed locations.
