### ISSUE TITLE
getProgramAccounts(PublicKey account, List<Memcmp> memcmpList) Doesn't offer Base64 equivalent

### ISSUE THREAD

**Issue by angusscott** [skynetcap/solanaj#64]
Believe that [getProgramAccounts(PublicKey account, List<Memcmp> memcmpList)](https://github.com/skynetcap/solanaj/blob/89f49ee5cd18ae422c10ff2e4ce0314092d764a7/src/main/java/org/p2p/solanaj/rpc/RpcApi.java#L268) should use a Base64 encoding, similar to [getProgramAccounts(PublicKey account, List<Memcmp> memcmpList, int dataSize)](https://github.com/skynetcap/solanaj/blob/89f49ee5cd18ae422c10ff2e4ce0314092d764a7/src/main/java/org/p2p/solanaj/rpc/RpcApi.java#L230)

You can find PR forked  [here](https://github.com/skynetcap/solanaj/pull/63), alternatively a method should be provided like [getProgramAccountsBase64(PublicKey account, long offset, String bytes)](https://github.com/skynetcap/solanaj/blob/89f49ee5cd18ae422c10ff2e4ce0314092d764a7/src/main/java/org/p2p/solanaj/rpc/RpcApi.java#L193)

**Comment by skynetcap** [comment]
Merged, thank you!

**Comment by angusscott** [comment]
Great thanks, @skynetcap any indication when next version will be out? Would be handy for something I'm working on just now :)
